### ISSUE TITLE
Don't compare with development images in readme

### ISSUE THREAD

**Issue by Hades32** [docker-slim/docker-slim#111]
That really doesn't make any sense. Nobody would (should?) use development images for their actual image. (Except for interpreted languages of course)

Comparing with Ubunutu/Alpine/BusyBox only makes more sense.

And for Go: many people already use FROM scratch. So it would be more interesting to point out what you gain with AppArmor etc

**Comment by kcq** [comment]
That's actually a lot more common then you'd think :) Well crafted and well optimized Dockerfiles are an exception...

Creating Go Docker images for relatively complex apps is not always straight forward because there's usually more to it then app binary. It's really easy to use the standard golang images and because it's so easy it happens more often than it should :)
