### ISSUE TITLE
ARM 64-bit not supported?

### ISSUE THREAD

**Issue by samip5** [docker-slim/docker-slim#155]
When building docker-slim on aarch64, the resulting binary is 32-bit, why?

I mean, it works as 32-bit too, but?

```bash
# go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_arm64"
GCCGO="gccgo"
AR="ar"
CC="aarch64-unknown-linux-gnu-gcc"
CXX="aarch64-unknown-linux-gnu-g++"
CGO_ENABLED="1"
GOMOD="/root/docker-slim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build278137245=/tmp/go-build -gno-record-gcc-switches"
```

```bash
# file ./dist_linux_arm/docker-slim
./dist_linux_arm/docker-slim: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=LAQxoMFJvO4r25jNM0xP/TSMB7tFj40z52UQeik7N/yDBwXDb_ShSqG0awNKC1/QB15mh4dHVGZ-106BRqy, stripped
```

**Comment by kcq** [comment]
@samip5 the build generates 3 different versions with the same target architectures regardless where it's built. Here's the line related to arm: https://github.com/docker-slim/docker-slim/blob/master/scripts/src.build.sh#L31 For arm64 we'll also need the syscall table like this https://github.com/docker-slim/docker-slim/blob/master/pkg/system/syscalls_armf32.go

I'll be happy to add a build for arm64 if you can help out with testing! If you'd like to contribute an arm64 syscall table that'll be nice too (otherwise i can create it too) :-)

**Comment by kadern0** [comment]
@kcq I've sent you a MR for the syscall table, also let me know if you need help for testing.

**Comment by kcq** [comment]
Awesome! Thank you @kadern0 ! Looking at the PR...

**Comment by kcq** [comment]
@kadern0 what did you use for the syscall numbers? can you add a reference to the source

**Comment by kadern0** [comment]
This is the file I've used:
https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/unistd.h

Couple things:

For this syscall, I've chosen the "sync_file_range" one:
```
#ifdef __ARCH_WANT_SYNC_FILE_RANGE2
#define __NR_sync_file_range2 84
__SC_COMP(__NR_sync_file_range2, sys_sync_file_range2, \
	  compat_sys_sync_file_range2)
#else
#define __NR_sync_file_range 84
__SC_COMP(__NR_sync_file_range, sys_sync_file_range, \
	  compat_sys_sync_file_range)
#endif 
```
I've also followed this comment:
```
/* 295 through 402 are unassigned to sync up with generic numbers, don't use */
```
And about the Go code itself, do you think it is necessary/useful redefining these constants instead of using the ones from arm32?
```
	SyscallArmUnknownNum64  = -1
	SyscallArmUnknownName64 = "unknown_syscall"
```
Thanks for your quick reply!

**Comment by kcq** [comment]
Thanks for the info @kadern0 ! It'll be interesting to verify if the  sync_file_range name is what seccomp will expect (which can be done separately).

Would you also be interested in updating the build script to generate the arm64 executables?

**Comment by kadern0** [comment]
@kcq I'll have a look later this afternoon to both things. I'll ping you if I find any problems.

**Comment by kcq** [comment]
Thank you!
