### ISSUE TITLE
Skip dynamic analysis

### ISSUE THREAD

**Issue by sundbry** [docker-slim/docker-slim#19]
Hello, I would like to crush a large image, without automatically deleting any files. Basically I just want to do manual clean-up at the end of my Dockerfile(s), and then flatten the image.

Could it provide an option to skip the runtime analysis?

**Comment by kcq** [comment]
So you are asking for an option to do more traditional static docker image optimization, right?

1. OS specific cleanup commands (optional)
2. Docker image flattening

This isn't possible now, but it's a good enhancement. DockerSlim is slowly expanding in that direction :-) In the meantime you might be interested in "docker-squash" because its main focus is on the traditional Docker image optimization you described.

**Comment by kcq** [comment]
Migrating to the wishlist.
