### ISSUE TITLE
Connection timeout in docker slim while reducing docker image size 

### ISSUE THREAD

**Issue by pradeepsr86** [docker-slim/docker-slim#22]
I tired to reduce my docker image size using docker slim but facing connection time out issue
i have used this command: ./docker-slim build --http-probe <my image-id> 

but got the below error

INFO[0008] docker-slim: http probe - GET http://127.0.0.1:32792/ error: Get http://127.0.0.1:32792/: dial tcp 127.0.0.1:32792: getsockopt: connection refused

INFO[0008] docker-slim: HTTP probe done.

INFO[0270] sendCmd(): receive timeout...

Can anyone help on this ??

**Comment by kcq** [comment]
Is there more to the command or './docker-slim build --http-probe' is the whole thing? Can you also set the debug flag, so the command looks like this: './docker-slim --debug build --http-probe your_image_id_or_name_here'.

What's your docker-slim version?

**Comment by natostanco** [comment]
sometimes the process gets stuck at `waiting for container to finish its work` despite the test container not actually running.
If the test container exits immediately it also gets stuck and after the retries limit end the process fails generating the apprarmor profile because no .json file is present

**Comment by kcq** [comment]
Sometime you might see HTTP connection errors if the HTTP probe wasn't done when you press enter. That error is harmless for the most part.

Either way, the master process sometimes gets stuck waiting for the temporary container to finish. It's really just stuck on the I/O waiting for the target to emit events. Need to replace the Mongos IPC library with something more reliable. It's on the official wishlist and it will be addressed soon.

**Comment by kcq** [comment]
Closing this one because it's pretty old. The recent releases add a number of HTTP probing enhancements, which should address problems like this either by doing a better job retrying or detecting that the target container is down. Try the latest release when you get a chance ( https://github.com/docker-slim/docker-slim/releases/tag/1.24 ). Thanks again for reporting the problem!
