### ISSUE TITLE
Problems when using a non-root user (workaround exists)

### ISSUE THREAD

**Issue by alecoletti** [docker-slim/docker-slim#35]
Hi!

I have an image based on node:6.9.2 where I'm following Docker-node best practices to avoid security issues [(check here)](https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md) but whenever I use a non-root user docker-slim is unable to build the image. [here is my Dockerfile](https://gist.github.com/alecoletti/30be3541a55c27b34e71e77514a7e44e), but you should be able to replicate the problem just by creating and using a non-root user e.g:

```
FROM node:6.9.2
# Add our user and group first to make sure their IDs get assigned consistently
RUN groupadd -r app && useradd -r -g app app

USER app

CMD ["node", "/usr/src/app/server.js"]
```

Any clues?

**Comment by kcq** [comment]
Thank you for the report Alessandro! I really appreciate it!

There's a potential workaround you might be able to use right now before the new version is out.

Workaround steps:

1. Don't add an explicit USER statement in your Dockerfile.

Note that you still need to have the RUN statement to execute the groupadd and useradd commands if you want to use a customer user. You can also stick with the 'node' user the node.js base images already have and, in that case, you don't need groupadd and useradd at all :-)

2. Explicitly include /etc/passwd when you minify your image with DockerSlim (using the --include-path docker-slim parameter).

Example: docker-slim --debug build --http-probe --include-path /etc/passwd your-docker-image-name

3. Use an explicit -u parameter in docker run.

Example: docker run -d -u "your-user-name" -p 8000:8000 your-minified-docker-image-name

Note that you should be able to avoid including /etc/passwd if you are ok with using UIDs instead of text user name in the -u parameter to docker run.

**Comment by kcq** [comment]
@alecoletti The new 1.24 release ( https://github.com/docker-slim/docker-slim/releases/tag/1.24 ) finally got support for non-default users. Let me know if the new release works for your images. Thanks again for raising the issue!

**Comment by kcq** [comment]
Closing it for now... Please reopen if you still see the same problem using non-default users.
