### ISSUE TITLE
Problem in /utils/dirs.go#CopyFile()

### ISSUE THREAD

**Issue by vintage-chou** [docker-slim/docker-slim#37]
Hi! 

I found when copying files, it could not copy the symbol links correctly.  It will always follow the symbol link, so some dependency issues will occur.

I think it should be 
```
func CopyFile(src, dst string, makeDir bool) error {
	info, err := os.Lstat(src)
        ...
}
```
instead of 
```
func CopyFile(src, dst string, makeDir bool) error {
	info, err := os.Stat(src)
        ...
}
```

**Comment by kcq** [comment]
Thank you for the report! What do you mean by "when copying files"? Are you using the utils package directly? The DockerSlim code uses it only when it needs to copy additional files based on the include-paths command line parameter. The main files DockerSlim discovers are copied using another method...

You are right about the Lstat() call though. There's a couple of other places with the same problem, but it's not relevant there because the files are already pre-filtered into regular and link files.

**Comment by vintage-chou** [comment]
Thank you for your reply!  Indeed, I use the utils package directly. And as you said, the ```CopyFile()``` has no effect on the main files DockerSlim discovers. 

I really appreciate docker-slim, thanks again.

**Comment by kcq** [comment]
It'll be fixed in a few days either way. Thank you for catching the bug!
