### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ZYecho** [docker-slim/docker-slim#70]
Hey all, I want to know this tool will decrease the number of layers or not? Or it only deletes the duplicate files between layers? Thanks :)

Another question is that does this tool can be applied to images such as golang/python/rust which doesn't run an application inside it.

**Comment by kcq** [comment]
It removes the layers and only keeps what your application needs and that's why you shouldn't use it on a vanilla base image. It's possible to do a few tricks to have a usable basic python image, for example, but you'll need to do a bit of extra work explicitly specifying the components you want to keep in your image using the `--include-path` or `--include-path-file` flags.
