### ISSUE TITLE
Question:What is the actual function of --http-probe?

### ISSUE THREAD

**Issue by hantmac** [docker-slim/docker-slim#78]
What is the actual function of `--http-probe`, can you explain in detail what happened when using --http-probe?

An advice: would u like to enrich the documentation? For example, a detailed description of the principle of some modules.

**Comment by kcq** [comment]
Definitely need better and more detailed docs!

This is an optional parameter that tells `docker-slim` that it should generate http/https calls when it creates its temporary container (the master app makes these calls against the open ports it finds in the target unless you specify the ports you care about explicitly). It's relevant for servers/services that expose web/http interfaces and APIs. It's a required option for some applications depending on the language used to build them. For example, Ruby-based servers need this because they do lazy loading for their application dependencies, so those HTTP calls force the application to load its dependencies when it handles the HTTP calls.

`--http-probe` is one of the http related commands. There's more :-) 

Here's the list:
--http-probe - enables HTTP probing (disabled by default)
--http-probe-cmd - additional HTTP probe command [zero or more]
--http-probe-cmd-file - file with user defined HTTP probe commands
--http-probe-retry-count - number of retries for each HTTP probe (default: 5)
--http-probe-retry-wait - number of seconds to wait before retrying HTTP probe (doubles when target is not ready; default: 8)
--http-probe-ports - explicit list of ports to probe (in the order you want them to be probed; excluded ports are not probed!)
--http-probe-full - do full HTTP probe for all selected ports (if false, finish after first successful scan; default: false)

There's more information about HTTP probing in this section: https://github.com/docker-slim/docker-slim#http-probe-commands

There's definitely an opportunity to improve this information and add more details :-) The information also needs to be restructured, so it's easier to find what you might need.

This is a great issue! Thank you for opening it! What are the other areas that you think can benefit from more detailed information?

**Comment by hantmac** [comment]
Thank you for your detailed reply！
You mean the docker-slim need use `http-probe` to get infomation from the docker image?

**Comment by kcq** [comment]
Yes. `docker-slim` uses probes to interact and understand the web services/applications in the container. It's a requirement for the python and ruby based services. For other languages it's optional.  You don't need it for dockerized command line applications though.

**Comment by kcq** [comment]
Next release will have HTTP probing turned on by default (unless you explicitly disable it).

**Comment by hantmac** [comment]
Got it! Thank you for your detailed reply！I hope that I can make some contributions to `docker-slim` someday, I'm trying my best to read the source code.

**Comment by kcq** [comment]
Any contribution will be greatly appreciated! Code or no code... More examples, bug reports or new docs are super important too :)
